### Bag Of Words Implementation

In [15]:
import pandas as pd
message=pd.read_csv("SMSSpamCollection.txt",sep="\t",names=["label","message"])

In [16]:
message

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [17]:
## Data Cleaning and preprocessing
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize,word_tokenize,wordpunct_tokenize
from nltk.stem import WordNetLemmatizer, SnowballStemmer,PorterStemmer
import re
lemmatizer=WordNetLemmatizer()

In [18]:
corpus=[]

for i in range(0,len(message)):
    review=re.sub('[^a-zA-z]',' ',message['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if word not in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)


In [19]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer=CountVectorizer(lowercase=True,stop_words='english',max_features=100,binary=True)

In [21]:
X=count_vectorizer.fit_transform(corpus).toarray()

In [22]:
count_vectorizer.vocabulary_

{'great': np.int64(22),
 'got': np.int64(21),
 'wat': np.int64(90),
 'ok': np.int64(57),
 'free': np.int64(17),
 'win': np.int64(93),
 'text': np.int64(76),
 'txt': np.int64(84),
 'say': np.int64(67),
 'think': np.int64(79),
 'life': np.int64(36),
 'hey': np.int64(28),
 'week': np.int64(92),
 'word': np.int64(94),
 'like': np.int64(37),
 'send': np.int64(68),
 'friend': np.int64(18),
 'customer': np.int64(11),
 'prize': np.int64(62),
 'claim': np.int64(7),
 'mobile': np.int64(47),
 'home': np.int64(30),
 'soon': np.int64(71),
 'want': np.int64(89),
 'tonight': np.int64(83),
 'today': np.int64(81),
 'cash': np.int64(6),
 'day': np.int64(13),
 'reply': np.int64(64),
 'urgent': np.int64(87),
 'www': np.int64(96),
 'right': np.int64(65),
 'help': np.int64(27),
 'time': np.int64(80),
 'message': np.int64(44),
 'com': np.int64(8),
 'oh': np.int64(56),
 'yes': np.int64(99),
 'make': np.int64(42),
 'way': np.int64(91),
 'feel': np.int64(16),
 'dont': np.int64(15),
 'miss': np.int64(46),
 'ur':

In [23]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### n_grams Implementation

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer=CountVectorizer(lowercase=True,stop_words='english',max_features=2500,binary=True,ngram_range=(1,3))

In [25]:
X=count_vectorizer.fit_transform(corpus).toarray()

In [26]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
count_vectorizer.vocabulary_

{'point': np.int64(1597),
 'crazy': np.int64(434),
 'available': np.int64(104),
 'bugis': np.int64(213),
 'great': np.int64(796),
 'world': np.int64(2429),
 'la': np.int64(1051),
 'cine': np.int64(314),
 'got': np.int64(788),
 'wat': np.int64(2327),
 'ok': np.int64(1462),
 'lar': np.int64(1064),
 'joking': np.int64(1024),
 'wif': np.int64(2387),
 'oni': np.int64(1481),
 'ok lar': np.int64(1465),
 'free': np.int64(687),
 'entry': np.int64(602),
 'wkly': np.int64(2414),
 'comp': np.int64(372),
 'win': np.int64(2393),
 'cup': np.int64(444),
 'final': np.int64(658),
 'st': np.int64(1934),
 'text': np.int64(2047),
 'receive': np.int64(1686),
 'question': np.int64(1653),
 'std': np.int64(1953),
 'txt': np.int64(2179),
 'rate': np.int64(1667),
 'apply': np.int64(64),
 'free entry': np.int64(694),
 'entry wkly': np.int64(605),
 'std txt': np.int64(1954),
 'txt rate': np.int64(2184),
 'rate apply': np.int64(1668),
 'free entry wkly': np.int64(696),
 'std txt rate': np.int64(1955),
 'txt rate ap

In [28]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### TF-IDF Implementation

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=100)


In [31]:
X=tfidf.fit_transform(corpus).toarray()

In [33]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,formatter=dict(float=lambda x:"%.3g"%x))

In [34]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0.571, 0, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.486, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

### TFIDF Implementation wit ngram

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=100,ngram_range=(2,2))

In [40]:
X=tfidf.fit_transform(corpus).toarray()

In [41]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,formatter=dict(float=lambda x:"%.3g"%x))

In [42]:
tfidf.vocabulary_

{'free entry': np.int64(32),
 'claim call': np.int64(15),
 'call claim': np.int64(3),
 'claim code': np.int64(16),
 'free call': np.int64(31),
 'chance win': np.int64(14),
 'txt word': np.int64(88),
 'let know': np.int64(54),
 'please call': np.int64(67),
 'lt gt': np.int64(58),
 'want go': np.int64(97),
 'like lt': np.int64(55),
 'sorry call': np.int64(79),
 'call later': np.int64(8),
 'ur awarded': np.int64(89),
 'hi hi': np.int64(46),
 'call customer': np.int64(4),
 'customer service': np.int64(23),
 'cash prize': np.int64(13),
 'po box': np.int64(69),
 'trying contact': np.int64(85),
 'draw show': np.int64(28),
 'show prize': np.int64(78),
 'prize guaranteed': np.int64(73),
 'guaranteed call': np.int64(42),
 'valid hr': np.int64(95),
 'selected receive': np.int64(75),
 'private account': np.int64(71),
 'account statement': np.int64(0),
 'statement show': np.int64(80),
 'call identifier': np.int64(5),
 'identifier code': np.int64(50),
 'code expires': np.int64(20),
 'urgent mobile':

In [43]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0