In [5]:
import numpy as np

##create arrays using numpy

#creating a 1d array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
arr2=np.array([1,2,3,4,5])
print(arr2.reshape(1,5)) #1 row and 5 cols
arr2.shape

[[1 2 3 4 5]]


(5,)

In [17]:
#2d array
arr3=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
(2, 6)


In [22]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
##identitity matrix

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 5)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 10
print("Data type:", arr.dtype)  # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3 4 5]
 [6 7 8 9 0]]
Shape: (2, 5)
Number of dimensions: 2
Size (number of elements): 10
Data type: int64
Item size (in bytes): 8


In [33]:
#numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#elementwise addition
print("addition:",arr1+arr2)

#element wise substraction
print("substraction:",arr1-arr2)

addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]


In [35]:

arr=np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [38]:
#array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
print(arr[0][0])

1


In [52]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1:3,2:4])

[[ 7  8]
 [11 12]]


In [51]:
arr[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [53]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [54]:
arr[0][0]=100

In [55]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [69]:
arr[1:,2:]=0

In [70]:
print(arr)

[[100   2   3   4]
 [  5   6   0   0]
 [  9  10   0   0]]


In [71]:
##statistical concept - normalization
#change data to have a mean of 0 and std deviation of 1

data =np.array([1,2,3,4,5])

#calc mean and std deviation
mean=np.mean(data)
std_dev=np.std(data)

#normalize data
normalized_data=(data-mean)/std_dev
print(f"normalized data: {normalized_data}")

normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [75]:
data= np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean=np.mean(data)
print(f"mean: {mean}")

#median
median=np.median(data)
print(f"median: {median}")

#standard deviation
std_dev=np.std(data)
print(f"standard deviation: {std_dev}")

#variance
variance=np.var(data)
print(f"variance: {variance}")

 

mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [85]:
#logical operations

data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])