In [5]:
import torch

In [6]:
import torch
print(torch.__version__)

2.7.0+cu118


In [7]:
import torch
print(torch.cuda.is_available())


True


In [8]:
import torch
print(torch.cuda.is_available())  # Should print True
print(torch.cuda.get_device_name())  # Should show your GPU name

True
NVIDIA GeForce GTX 1660 Ti with Max-Q Design


- a torch.Tensor is a multi dimensional matrix cntaining elements of a single data type.
- similar to numpy arrays, but full of fun  things that make them work better on gpus vs regular cpus.
- default data type of float32.
- more suitable for deep learning than a numpy array.

In [9]:
import torch
import numpy as np

In [13]:
#numpy arrays

np1=np.random.rand(3,4)
print(np1)
print(np1.dtype)

[[0.74488704 0.37913168 0.72651791 0.29682957]
 [0.47453249 0.21334431 0.38906345 0.88145231]
 [0.07319936 0.63103673 0.40762054 0.83700311]]
float64


Tensors

In [ ]:
#2 dimensional
tensor=torch.randn(3,4)
tensor

tensor([[ 1.5885,  0.5957, -0.1620, -0.0567],
        [ 1.9813,  0.2722,  0.5863,  0.4585],
        [-1.6148,  1.2253, -0.8909, -1.6279]])

In [22]:
#3 dimendional
tensor2=torch.randn(2,3,4)
print(tensor2)
print(tensor2.dtype)

tensor([[[-1.5568,  0.2734, -2.1973,  0.6591],
         [ 0.3655, -0.4375, -0.2806,  0.7563],
         [ 1.2645, -1.5710, -0.5049,  0.8445]],

        [[-0.8055, -0.8481, -0.3073,  0.7815],
         [ 0.9361, -0.1701, -0.0330, -0.1475],
         [ 0.9495, -0.2328, -0.2631,  0.6720]]])
torch.float32


In [21]:
#create tensor out of numpy array
array_to_tensor=torch.tensor(np1)
array_to_tensor

tensor([[0.7449, 0.3791, 0.7265, 0.2968],
        [0.4745, 0.2133, 0.3891, 0.8815],
        [0.0732, 0.6310, 0.4076, 0.8370]], dtype=torch.float64)

Tensor Operations - Reshape and slice

In [24]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Reshape

my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [35]:
# reshape if we dont know the number of items
my_torch2=torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
my_torch2=my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
#view
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
my_torch3=my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

changes in one variable makes changes to another variable in reshape and view

In [51]:
my_torch4=torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
my_torch5=my_torch4.reshape(2,-1)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [54]:
my_torch4[1]=50
my_torch4

tensor([ 0, 50,  2,  3,  4,  5,  6,  7,  8,  9])

In [55]:
my_torch5

tensor([[ 0, 50,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

we can see that my_torch5 was a reshaped version of my_torch4 and that any changes to my_torch4 made changes to my_torch5 as well

Slicing

In [57]:
my_torch7=torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
my_torch7[:5:]

tensor([0, 1, 2, 3, 4])

In [65]:
my_torch8=my_torch7.reshape(2,-1)
my_torch8

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [81]:
my_torch8[1,0:2:1]

tensor([5, 6])

Tensor Math Operation- Add, Sub, Div, Mul, Remainders, Exponents, Shorthand, Longhand, Reassignment

In [88]:
my_torch9=torch.tensor([1,1.234,1.0])
my_torch9.dtype

torch.float32