Naive Bayes Machine Learning Implementation

In [68]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [69]:
X,y=load_iris(return_X_y=True)

In [70]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [71]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [72]:
#train test split
X_Train, X_test, y_train,y_test=train_test_split(X,y,test_size=0.3, random_state=0)

In [73]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()

In [74]:
nb.fit(X_Train,y_train)

GaussianNB()

In [75]:
y_hat_test=nb.predict(X_test)

In [76]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [77]:
print(accuracy_score(y_test,y_hat_test))
print(confusion_matrix(y_test,y_hat_test))
print(classification_report(y_test,y_hat_test))

1.0
[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [78]:
import seaborn as sns

In [79]:
df=sns.load_dataset('tips')

In [80]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [81]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [83]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()


In [84]:
X=df[['total_bill','tip','sex','smoker','day','size']]
y=df[['time']]

In [85]:
y

time
0    Dinner
1    Dinner
2    Dinner
3    Dinner
4    Dinner
..      ...
239  Dinner
240  Dinner
241  Dinner
242  Dinner
243  Dinner

[244 rows x 1 columns]

In [86]:
X

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [87]:
X_Train, X_test, y_train,y_test=train_test_split(X,y,test_size=0.3, random_state=0)

In [88]:
y_train

time
61   Dinner
146   Lunch
52   Dinner
66   Dinner
26   Dinner
..      ...
67   Dinner
192   Lunch
117   Lunch
47   Dinner
172  Dinner

[170 rows x 1 columns]

In [89]:
X_Train['sex']=le1.fit_transform(X_Train['sex'])
X_Train['smoker']=le2.fit_transform(X_Train['smoker'])


In [90]:
X_test['sex']=le1.transform(X_test['sex'])
X_test['smoker']=le2.transform(X_test['smoker'])

In [91]:
y_train['time']=le3.fit_transform(y_train['time'])
y_test['time']=le3.transform(y_test['time'])

In [92]:
X_Train

total_bill   tip  sex  smoker   day  size
61        13.81  2.00    1       1   Sat     2
146       18.64  1.36    0       0  Thur     3
52        34.81  5.20    0       0   Sun     4
66        16.45  2.47    0       0   Sat     2
26        13.37  2.00    1       0   Sat     2
..          ...   ...  ...     ...   ...   ...
67         3.07  1.00    0       1   Sat     1
192       28.44  2.56    1       1  Thur     2
117       10.65  1.50    0       0  Thur     2
47        32.40  6.00    1       0   Sun     4
172        7.25  5.15    1       1   Sun     2

[170 rows x 6 columns]

In [93]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder()

In [94]:
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[('one hot',OneHotEncoder(drop='first'),[4])],remainder='passthrough')

X_Train=ct.fit_transform(X_Train)
X_test=ct.transform(X_test)

In [97]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

X_Train

array([[ 1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.64,  1.36,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 34.81,  5.2 ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 16.45,  2.47,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.37,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.26,  3.25,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  8.51,  1.25,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.59,  1.5 ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 16.04,  2.24,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 18.43,  3.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 23.68,  3.31,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.26,  2.74,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 19.82,  3.18,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  9.55,  1.45,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  7.74,  1.44,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.

In [98]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [95]:
X_test

array([[ 1.  ,  0.  ,  0.  , 17.59,  2.64,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 19.49,  3.51,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  7.25,  1.  ,  0.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  , 16.27,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  5.75,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  3.08,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.15,  3.5 ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 34.65,  3.68,  1.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 25.28,  5.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 25.21,  4.29,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 14.07,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.  ,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 13.42,  1.58,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.

In [99]:
#implementing naive bayes

from sklearn.naive_bayes import GaussianNB

nb=GaussianNB()

nb.fit(X_Train,y_train)

c:\Data-science-Course-AtoZ-Krishnaik\venv\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [100]:
y_hat_test=nb.predict(X_test)

In [101]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [102]:
print(accuracy_score(y_test,y_hat_test))
print(confusion_matrix(y_test,y_hat_test))
print(classification_report(y_test,y_hat_test))

0.918918918918919
[[55  1]
 [ 5 13]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95        56
           1       0.93      0.72      0.81        18

    accuracy                           0.92        74
   macro avg       0.92      0.85      0.88        74
weighted avg       0.92      0.92      0.92        74

